name: Code Quality and Deployment Workflow with Flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can diff

    - name: Install Flake8
      run: pip install flake8

    - name: Get list of changed files
      id: getfile
      run: |
        git fetch origin ${{ github.event.before }}  # Fetch the base commit
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

    - name: Run Flake8 on changed files
      run: |
        if [ ! -z "$CHANGED_FILES" ]; then
          echo $CHANGED_FILES | xargs flake8
        else
          echo "No files have changed."
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 18.212.172.79
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "cd test-CI-CD && git pull origin main"
        rm -f private_key.pem
