name: Code Quality and Deployment Workflow with Flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    # - name: Set up Python
    #   uses: actions/setup-python@v3  # Updated to latest version
    #   with:
    #     python-version: '3.8'

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8

  deploy:
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 18.212.172.79
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "cd test-CI-CD && git pull origin main"
        rm -f private_key.pem
